calculator:
  title: Smart Pants Calculator
  width: 400
  height: 250
  components:
    identity:
      x: ${calculator.components.left-number.x}
      y: 25
      width: 300
      height: 50
    left-number:
      label: 'left:'
      x: 25
      y: 95
      width: 225
      height: 25
    right-number:
      label: 'right:'
      x: ${calculator.components.left-number.x}
      y: 125
      width: ${calculator.components.left-number.width}
      height: ${calculator.components.left-number.height}
    add-button:
      title: add
      x: 250
      y: ${calculator.components.left-number.y}
      width: 60
      height: ${calculator.components.left-number.height}
    sub-button:
      title: sub
      x: ${calculator.components.add-button.x}
      y: ${calculator.components.right-number.y}
      width: ${calculator.components.add-button.width}
      height: ${calculator.components.add-button.height}
    mult-button:
      title: mult
      x: 315
      y: ${calculator.components.left-number.y}
      width: ${calculator.components.add-button.width}
      height: ${calculator.components.add-button.height}
    div-button:
      title: div
      x: ${calculator.components.mult-button.x}
      y: ${calculator.components.right-number.y}
      width: ${calculator.components.add-button.width}
      height: ${calculator.components.add-button.height}
    result:
      label: 'result:'
      init-value: 'will be here...'
      x: ${calculator.components.left-number.x}
      y: 170
      width: ${calculator.components.left-number.width}
      height: ${calculator.components.left-number.height}
