calculator:
  title: Smart Pants Calculator
  width: 500
  height: 200
  components:
    left-number:
      label: 'left:'
      x: 25
      y: 25
      width: 250
      height: 25
    right-number:
      label: 'right:'
      x: ${calculator.components.left-number.x}
      y: 75
      width: ${calculator.components.left-number.width}
      height: ${calculator.components.left-number.height}
    add-button:
      title: add
      x: 300
      y: ${calculator.components.left-number.y}
      width: 60
      height: ${calculator.components.left-number.height}
    sub-button:
      title: sub
      x: ${calculator.components.add-button.x}
      y: ${calculator.components.right-number.y}
      width: ${calculator.components.add-button.width}
      height: ${calculator.components.add-button.height}
    mult-button:
      x: 300
    div-button:
      x: 300
    result:
      label: 'result:'
      init-value: 'will be here...'
      x: ${calculator.components.left-number.x}
      y: 125
      width: ${calculator.components.left-number.width}
      height: ${calculator.components.left-number.height}
